image: debian:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive

stages:
  - build

build:
  stage: build
  before_script:
    # install dependencies
    - apt-get update && apt-get install -y build-essential wget cmake bison flex libssl1.1 libssl-dev openmpi-bin libopenmpi-dev
    #  install spot
    - wget -q -O - https://www.lrde.epita.fr/repo/debian.gpg | apt-key add -
    - echo 'deb http://www.lrde.epita.fr/repo/debian/ stable/' >> /etc/apt/sources.list
    - apt-get update && apt-get install -y spot libspot-dev
  script:
    - cmake -S . -B build
    - cmake --build build --target install
  artifacts:
    paths:
      - assets/pmc-sog
    expire_in: 1 week
